//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUYETTINTUC
    {
        public string MaDuyetTin { get; set; }
        public System.DateTime ThoiGianDuyet { get; set; }
        public int MaTinTuc { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayDuocDang { get; set; }
    }
}
