//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH
    {
        public string IDHinh { get; set; }
        public string Hinh1 { get; set; }
        public int MaTinTuc { get; set; }
    }
}
