//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTinTuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebTinTucEntities : DbContext
    {
        public WebTinTucEntities()
            : base("name=WebTinTucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DANGTINTUC> DANGTINTUCs { get; set; }
        public virtual DbSet<DUYETTINTUC> DUYETTINTUCs { get; set; }
        public virtual DbSet<HINH> HINHs { get; set; }
        public virtual DbSet<LOAITIN> LOAITINs { get; set; }
        public virtual DbSet<SUATIN> SUATINs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
        public virtual DbSet<TINTUC> TINTUCs { get; set; }
        public virtual DbSet<TUKHOA> TUKHOAs { get; set; }
    }
}
