//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUATIN
    {
        public string MaSuaTin { get; set; }
        public int MaTinTuc { get; set; }
        public System.DateTime ThoiGianSua { get; set; }
        public string ID { get; set; }
        public string LinkFile { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
